[package]
name = "int_data_analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.6.0"
linfa-clustering = "0.6.0"
linfa-datasets = { version = "0.6.0", features = ["generate"] }
rand = "0.8.5"
ndarray = {version = "0.15.6", features = ["approx-0_5"]}
ndarray-rand = "0.14.0"
rand_xoshiro = "0.6.0"
approx = "0.5.1"
csv = "1.1.6"

[profile.dev]
lto = true          # Enable Link Time Optimization
